#define MQTT_USERNAME ""
#define MQTT_PASSWORD ""
#define MQTT_HOST "127.0.0.1"
#define MQTT_PORT 1883

#define OPEN_SENSOR_MSG "OPEN"
#define CLOSED_SENSOR_MSG "CLOSED"
#define TAMPER_MSG "TAMPER"
#define UNTAMPERED_MSG "OK"
#define LOW_BAT_MSG "LOW"
#define OK_BAT_MSG "OK"
